version: '3'
services:
  app:
    build:
      context: .
    ports:
      - "4006:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - ./localStorage:/app/localStorage
    environment:
      - NODE_ENV=development
    command: npm run dev
